name: Create Release

on:
  workflow_dispatch: 
  #push:
  #  branches:
  #    - 'main'
  #    - 'master'
  #  paths:
  #    - 'lean-toolchain'

jobs:
  build:
    if: false  # This prevents the workflow from running
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Workflow disabled"
  lean-release-tag:
    name: Add Lean release tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: lean-release-tag action
      uses: leanprover-community/lean-release-tag@v1
      with:
        do-release: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
