name: Lean Action CI

on:
  workflow_dispatch:  
#  push:
#  pull_request:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read # Read access to repository contents
  pages: write # Write access to GitHub Pages
  id-token: write # Write access to ID tokens

jobs:
  build:
    if: false  # This prevents the workflow from running
    runs-on: ubuntu-latest
    steps:
      - name: Placeholder
        run: echo "Workflow disabled"
#  build:
#    runs-on: ubuntu-latest

#    steps:
#      - uses: actions/checkout@v4
#      - uses: leanprover/lean-action@v1
#      - uses: leanprover-community/docgen-action@v1
